import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        {/*
          Script de inicialización de tema admin.
          Se ejecuta de forma síncrona antes del primer paint para evitar
          el flash de colores por defecto.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var b=JSON.parse(localStorage.getItem('aion_tenant_branding')||'null');if(b&&b.primary){var r=document.documentElement;r.style.setProperty('--admin-primary',b.primary);r.style.setProperty('--admin-secondary',b.secondary);r.style.setProperty('--admin-accent',b.accent);r.style.setProperty('--admin-bg',b.background);r.style.setProperty('--admin-sidebar-bg',b.primary);r.style.setProperty('--admin-sidebar-bg-2',b.secondary);}}catch(e){}}())`,
          }}
        />
        {children}
      </body>
    </html>
  );
}
