export const menuImageMap: Record<string, string> = {
  "smoothies::mango-naranja": "/assets/menu/01_smoothies_mango-naranja.png",
  "smoothies::fresa-naranja-limon":
    "/assets/menu/02_smoothies_fresa-naranja-limon.png",
  "smoothies::fresa-naranja-banano":
    "/assets/menu/03_smoothies_fresa-naranja-banano.png",
  "smoothies::pina-naranja-mora":
    "/assets/menu/04_smoothies_pina-naranja-mora.png",
  "smoothies::pina-naranja-banano":
    "/assets/menu/05_smoothies_pina-naranja-banano.png",
  "cervezas::bbc": "/assets/menu/06_cervezas_bbc.png",
  "cervezas::3-cordilleras": "/assets/menu/07_cervezas_3-cordilleras.png",
  "cervezas::club-colombia": "/assets/menu/08_cervezas_club-colombia.png",
  "cervezas::corona": "/assets/menu/09_cervezas_corona.png",
  "cervezas::stella": "/assets/menu/10_cervezas_stella.png",
  "cocteles::colimocho": "/assets/menu/11_cocteles_colimocho.png",
  "cocteles::tinto-de-verano": "/assets/menu/12_cocteles_tinto-de-verano.png",
  "cocteles::mojito": "/assets/menu/13_cocteles_mojito.png",
  "cocteles::cuba-libre": "/assets/menu/14_cocteles_cuba-libre.png",
  "cocteles::muller": "/assets/menu/15_cocteles_muller.png",
  "cocteles::margarita": "/assets/menu/16_cocteles_margarita.png",
  "sangria::copa-sangria": "/assets/menu/17_sangria_copa-sangria.png",
  "sangria::jarra-x2": "/assets/menu/18_sangria_jarra-x2.png",
  "sangria::jarra-x5": "/assets/menu/19_sangria_jarra-x5.png",
  "vino::vino-casa": "/assets/menu/20_vino_vino-casa.png",
  "vino::vino-rosado": "/assets/menu/21_vino_vino-rosado.png",
  "vino::vino-blanco": "/assets/menu/22_vino_vino-blanco.png",
  "vino::merlot": "/assets/menu/23_vino_merlot.png",
  "entradas::maiz-sencillo": "/assets/menu/24_entradas_maiz-sencillo.png",
  "entradas::maiz-especial": "/assets/menu/25_entradas_maiz-especial.png",
  "entradas::nachos": "/assets/menu/26_entradas_nachos.png",
  "entradas::cazuela-pequena": "/assets/menu/27_entradas_cazuela-pequena.png",
  "entradas::cazuela-grande": "/assets/menu/28_entradas_cazuela-grande.png",
  "entradas::tabla-de-queso": "/assets/menu/29_entradas_tabla-de-queso.png",
  "entradas::combinado-iberico":
    "/assets/menu/30_entradas_combinado-iberico.png",
  "cafes::expreso": "/assets/menu/31_cafes_expreso.png",
  "cafes::americano": "/assets/menu/32_cafes_americano.png",
  "cafes::capuchino": "/assets/menu/33_cafes_capuchino.png",
  "cafes::moka-caliente": "/assets/menu/34_cafes_moka-caliente.png",
  "cafes::carajillo-amaretto": "/assets/menu/35_cafes_carajillo-amaretto.png",
  "cafes::carajillo-whisky": "/assets/menu/36_cafes_carajillo-whisky.png",
  "cafes::carajillo-vino": "/assets/menu/37_cafes_carajillo-vino.png",
  "cafes::carajillo-conac": "/assets/menu/38_cafes_carajillo-conac.png",
  "cafes::carajillo-ron": "/assets/menu/39_cafes_carajillo-ron.png",
  "cafes::latte-macchiato": "/assets/menu/40_cafes_latte-macchiato.png",
  "cafes::irlandes": "/assets/menu/41_cafes_irlandes.png",
  "cafes::cafe-helado": "/assets/menu/42_cafes_cafe-helado.png",
  "cafes::moka-frio": "/assets/menu/43_cafes_moka-frio.png",
  "cafes::frapuchino": "/assets/menu/44_cafes_frapuchino.png",
  "cafes::aromatica-tradicional":
    "/assets/menu/45_cafes_aromatica-tradicional.png",
  "cafes::aromatica-frutos-rojos":
    "/assets/menu/46_cafes_aromatica-frutos-rojos.png",
  "cafes::te-chai": "/assets/menu/47_cafes_te-chai.png",
  "postres::brownie": "/assets/menu/48_postres_brownie.png",
  "postres::fresas-chantilli": "/assets/menu/49_postres_fresas-chantilli.png",
  "sandwiches::iberico": "/assets/menu/50_sandwiches_iberico.png",
  "sandwiches::il-cafeto-mixto":
    "/assets/menu/51_sandwiches_il-cafeto-mixto.png",
  "sandwiches::tradicional": "/assets/menu/52_sandwiches_tradicional.png",
  "sandwiches::hawaiano": "/assets/menu/53_sandwiches_hawaiano.png",
  "sandwiches::pollo": "/assets/menu/54_sandwiches_pollo.png",
  "sandwiches::pollo-desmechado":
    "/assets/menu/55_sandwiches_pollo-desmechado.png",
  "sandwiches::carne-desmechada":
    "/assets/menu/56_sandwiches_carne-desmechada.png",
  "sandwiches::bacon": "/assets/menu/57_sandwiches_bacon.png",
  "sandwiches::vegetariano": "/assets/menu/58_sandwiches_vegetariano.png",
  "sandwiches::atun": "/assets/menu/59_sandwiches_atun.png",
  "sandwiches::cerdo": "/assets/menu/60_sandwiches_cerdo.png",
  "carnes::brocheta-de-cerdo": "/assets/menu/61_carnes_brocheta-de-cerdo.png",
  "carnes::pechuga-gratinada": "/assets/menu/62_carnes_pechuga-gratinada.png",
  "carnes::canon": "/assets/menu/63_carnes_canon.png",
  "carnes::milanesa": "/assets/menu/64_carnes_milanesa.png",
  "carnes::solomito": "/assets/menu/65_carnes_solomito.png",
  "carnes::salmon": "/assets/menu/66_carnes_salmon.png",
  "ensaladas::ensalada-en-bowl":
    "/assets/menu/67_ensaladas_ensalada-en-bowl.png",
  "adiciones::adicion-queso": "/assets/menu/68_adiciones_adicion-queso.png",
  "adiciones::champinones": "/assets/menu/69_adiciones_champinones.png",
  "adiciones::tocineta": "/assets/menu/70_adiciones_tocineta.png",
  "bebidas::limonada-natural": "/assets/menu/71_bebidas_limonada-natural.png",
  "bebidas::limonada-lychee": "/assets/menu/72_bebidas_limonada-lychee.png",
  "bebidas::coco": "/assets/menu/73_bebidas_coco.png",
  "bebidas::cereza": "/assets/menu/74_bebidas_cereza.png",
  "bebidas::hierbabuena": "/assets/menu/75_bebidas_hierbabuena.png",
  "bebidas::pina-hierbabuena": "/assets/menu/76_bebidas_pina-hierbabuena.png",
  "bebidas::jugo-agua": "/assets/menu/77_bebidas_jugo-agua.png",
  "bebidas::jugo-leche": "/assets/menu/78_bebidas_jugo-leche.png",
  "bebidas::avena": "/assets/menu/79_bebidas_avena.png",
  "bebidas::milo-frio": "/assets/menu/80_bebidas_milo-frio.png",
  "bebidas::botella-agua": "/assets/menu/81_bebidas_botella-agua.png",
  "bebidas::soda-michelada": "/assets/menu/82_bebidas_soda-michelada.png",
  "bebidas::soda-saborizada": "/assets/menu/83_bebidas_soda-saborizada.png",
  "bebidas::batido-de-proteina":
    "/assets/menu/84_bebidas_batido-de-proteina.png",
};
